### ISSUE TITLE
Adding middleware by classname misleading

### ISSUE THREAD

**Issue by XedinUnknown** [northwoods/broker#11]
The documentation in the readme states:

> When a container is provided middleware can be added by class name

But this is only true if the keys of middleware services are their class names. In any other case, this is not true. I found this to be very misleading, as it lead me to wonder about how middleware is resolved from the container by class name. Instead, it seems more clear to explain that the middleware will be retrieved from the container by key.

**Comment by shadowhand** [comment]
The documentation is wrong, any string can be used in combination with a container. Personally, I don't use any container that identifies entries by anything other than class, hence the mistake.

**Comment by shadowhand** [comment]
PRs welcome.
