### ISSUE TITLE
Proposal: Mapping path prefixes to middleware stacks

### ISSUE THREAD

**Issue by franzliedke** [northwoods/broker#6]
**I will happily implement this and send a pull request, if you agree with the idea.**

What do you think about something like this?

```php
$broker->paths([
  '/foo' => $myMiddlewareStack,
  '/bar' => MyMiddleware::class,
  '/baz' => 'baz.middleware.stack'
]);
```

Array values can be middleware, or strings which would then be **lazily** resolved from the container, whenever a request with this prefix arrives.

This method would have to take care of stripping the path prefix from the request object.

**Comment by franzliedke** [comment]
A little bit of background: If it had this functionality, I would gladly use this library in [Flarum](https://github.com/flarum/core) in order to use PSR-15 middleware. We're currently using Zend's Stratigility, but their PSR-15-compatible version does not support PHP 7.0, which is - currently - still a requirement on our side.

**Comment by shadowhand** [comment]
Would adding this functionality introduce new dependencies? I like the idea of it.

For whatever it's worth, the functionality is already possible by doing something like this:

```php
$broker->when($this->matchesPath('/foo'), MyMiddleware::class);
```

Assuming that:

```php
private function matchesPath(string $path): callable
{
    return static function (RequestInterface $request) use ($path): bool {
        return strpos($request->getUri()->getPath(), $path) === 0;
    };
}
```

**Comment by franzliedke** [comment]
I would implement it without external dependencies.

Stratigility additionally strips out the path prefix from the request - which is very useful because the middleware does not need to know about the prefix. So just `matchesPath` is not enough.

@shadowhand Is that a "go ahead" then? :grinning:

**Comment by shadowhand** [comment]
@franzliedke sure, I'd definitely consider a PR. Seems like it will be reasonable.

**Comment by franzliedke** [comment]
Little status update:
I got path matching working. The only thing remaining is to change the request's URI object so that subsequent middleware does not have to know about the path prefix.

**Comment by shadowhand** [comment]
Closing, see discussion on #7
